/**
 * Export targets.
 *
 * The web app is the editor; something else has to actually render the panels
 * on the glasses. These exporters produce that something:
 *
 * - `profileJson` — the portable source of truth, re-importable here.
 * - `unityApplier` — C# for a Unity project using the RayNeo Air SDK. Every
 *   device setting is emitted as the real `NativeModule` call, and every panel
 *   becomes a world-space quad at the right angle and distance.
 * - `androidIntent` — an `adb` one-liner for handing a profile to a companion.
 */

import type { Profile, Panel, Workspace } from './types'
import { getDevice } from './device'
import { analysePanel, devicePpd, panelSizeM, splitFov } from './optics'
import { ipdMmToNormalised } from './bridge'

export function profileJson(profile: Profile): string {
  return JSON.stringify(profile, null, 2)
}

export function parseProfile(text: string): Profile {
  const parsed = JSON.parse(text) as Profile
  if (typeof parsed !== 'object' || parsed === null) throw new Error('Not an object')
  if (parsed.schemaVersion !== 2) {
    throw new Error(
      `Unsupported schemaVersion ${String(parsed.schemaVersion)} — expected 2`,
    )
  }
  if (!Array.isArray(parsed.workspaces) || parsed.workspaces.length === 0) {
    throw new Error('Profile has no workspaces')
  }
  for (const ws of parsed.workspaces) {
    if (!Array.isArray(ws.panels) || !Array.isArray(ws.views)) {
      throw new Error(`Workspace "${ws.name ?? ws.id}" is missing panels or views`)
    }
    for (const p of ws.panels) {
      if (typeof p.faceWearer !== 'boolean') p.faceWearer = true
    }
  }
  return parsed
}

const cs = (s: string) => s.replace(/["\\]/g, '\\$&')
const f = (n: number) => `${Number(n.toFixed(4))}f`

/**
 * Emit a Unity `MonoBehaviour` that reproduces a workspace on the glasses.
 *
 * The geometry is baked to metres and Unity's left-handed, Y-up, +Z-forward
 * convention rather than shipped as angles, so the runtime side stays trivial
 * and there is only one place the spherical-to-Cartesian conversion happens.
 */
export function unityApplier(profile: Profile): string {
  const device = getDevice(profile.deviceId)
  const ws =
    profile.workspaces.find((w) => w.id === profile.activeWorkspaceId) ??
    profile.workspaces[0]!
  const fov = splitFov(device.fovDiagonalDeg, device.panelWidthPx / device.panelHeightPx)
  const ppd = devicePpd(device)

  const panelLines = ws.panels
    .map((p) => {
      const { widthM, heightM } = panelSizeM(p.diagonalIn, p.aspect)
      const a = analysePanel(p, device)
      return `            new PanelSpec {
                Id = "${cs(p.id)}",
                Title = "${cs(p.title)}",
                Source = "${cs(p.source)}",
                YawDeg = ${f(p.yawDeg)}, PitchDeg = ${f(p.pitchDeg)}, RollDeg = ${f(p.rollDeg)},
                DistanceM = ${f(p.distanceM)},
                WidthM = ${f(widthM)}, HeightM = ${f(heightM)},
                SourceWidthPx = ${p.sourceWidthPx}, SourceHeightPx = ${p.sourceHeightPx},
                Anchor = AnchorMode.${p.anchor === 'head' ? 'Head' : p.anchor === 'body' ? 'Body' : 'World'},
                FaceWearer = ${p.faceWearer ? 'true' : 'false'},
                Opacity = ${f(p.opacity)}, CurvatureDeg = ${f(p.curvatureDeg)},
                ZOrder = ${p.zOrder}, Visible = ${p.visible ? 'true' : 'false'},
                DimWhenUnfocused = ${p.dimWhenUnfocused ? 'true' : 'false'},
                // ${a.angularWidthDeg.toFixed(1)}° x ${a.angularHeightDeg.toFixed(
                  1,
                )}° · ${Math.round(a.sharpness * 100)}% of source resolution
            },`
    })
    .join('\n')

  const viewLines = ws.views
    .map(
      (v) => `            new ViewSpec {
                Id = "${cs(v.id)}",
                Name = "${cs(v.name)}",
                Hotkey = "${cs(v.hotkey ?? '')}",
                RecenterOnEnter = ${v.recenterOnEnter ? 'true' : 'false'},
                FocusedPanelId = "${cs(v.focusedPanelId ?? '')}",
                PanelIds = new [] { ${v.panelIds.map((i) => `"${cs(i)}"`).join(', ')} },
            },`,
    )
    .join('\n')

  return `// <auto-generated>
// RayNeo Air 4 Pro workspace applier
//
// Generated by the RayNeo Workspace Configurator from profile "${cs(profile.name)}"
// Workspace: "${cs(ws.name)}"   Target: ${cs(device.name)}
//
// Drop this on a GameObject in a Unity project that has the RayNeo Air SDK
// (Ffalcon XR Unity SDK) imported, assign PanelPrefab, and press play. Device
// settings go out through NativeModule; panels are built as world-space quads.
//
// Device reference:
//   Per-eye resolution   ${device.panelWidthPx} x ${device.panelHeightPx}
//   Field of view        ${device.fovDiagonalDeg}° diagonal (${fov.horizontalDeg.toFixed(
    1,
  )}° x ${fov.verticalDeg.toFixed(1)}°)
//   On-axis density      ${ppd.center.toFixed(1)} px/deg
//   Tracking            ${device.dof}DoF — orientation only, no positional tracking
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;

namespace RayNeo.Workspace
{
    public enum AnchorMode { Head, Body, World }

    [Serializable]
    public class PanelSpec
    {
        public string Id;
        public string Title;
        public string Source;
        public float YawDeg, PitchDeg, RollDeg;
        public float DistanceM;
        public float WidthM, HeightM;
        public int SourceWidthPx, SourceHeightPx;
        public AnchorMode Anchor;
        public bool FaceWearer;
        public float Opacity;
        public float CurvatureDeg;
        public int ZOrder;
        public bool Visible;
        public bool DimWhenUnfocused;
    }

    [Serializable]
    public class ViewSpec
    {
        public string Id;
        public string Name;
        public string Hotkey;
        public bool RecenterOnEnter;
        public string FocusedPanelId;
        public string[] PanelIds;
    }

    public class RayNeoWorkspaceApplier : MonoBehaviour
    {
        [Header("Scene wiring")]
        [Tooltip("Quad prefab used for every panel. Needs a MeshRenderer.")]
        public GameObject PanelPrefab;

        [Tooltip("The Head transform from the XRPlugin prefab.")]
        public Transform Head;

        [Tooltip("Parent for Body-anchored panels. Follows head yaw with lag.")]
        public Transform BodyRig;

        [Header("Device settings")]
        [Range(0, 3)] public int LuminanceMode = ${profile.device.luminanceMode};
        [Range(60f, 70f)] public float IpdMm = ${f(profile.device.ipdMm)};
        [Range(-10, 10)] public int FovScale = ${profile.device.fovScale};
        public bool ShowFovControlView = ${profile.device.fovControlView ? 'true' : 'false'};

        [Header("Body anchor follow")]
        public float FollowDeadzoneDeg = ${f(profile.device.followDeadzoneDeg)};
        public float FollowLagSeconds = ${f(profile.device.followLagS)};

        // Hardware constants for the target device.
        public const int PanelWidthPx = ${device.panelWidthPx};
        public const int PanelHeightPx = ${device.panelHeightPx};
        public const float FovDiagonalDeg = ${f(device.fovDiagonalDeg)};
        public const float FovHorizontalDeg = ${f(fov.horizontalDeg)};
        public const float FovVerticalDeg = ${f(fov.verticalDeg)};
        public const float IpdMinMm = ${f(device.ipdRangeMm[0])};
        public const float IpdMaxMm = ${f(device.ipdRangeMm[1])};

        public static readonly PanelSpec[] Panels = new []
        {
${panelLines}
        };

        public static readonly ViewSpec[] Views = new []
        {
${viewLines}
        };

        private readonly Dictionary<string, GameObject> _instances = new Dictionary<string, GameObject>();
        private readonly Dictionary<string, PanelSpec> _specs = new Dictionary<string, PanelSpec>();
        private ViewSpec _activeView;
        private string _focusedPanelId;
        private float _bodyYaw;

        void Start()
        {
            foreach (var p in Panels) _specs[p.Id] = p;
            ApplyDeviceSettings();
            BuildPanels();
            ActivateView("${cs(ws.activeViewId)}");
        }

        // -------------------------------------------------------------------
        // Device settings — these are the calls the RayNeo Air SDK exposes.
        // -------------------------------------------------------------------

        public void ApplyDeviceSettings()
        {
            // Four discrete brightness steps; the SDK has no continuous control.
            NativeModule.Instance.SetLuminanceMode(LuminanceMode);

            // SetInterpupilDistance takes a normalised 0..1 mapped onto ${device.ipdRangeMm[0]}-${device.ipdRangeMm[1]} mm.
            NativeModule.Instance.SetInterpupilDistance(NormaliseIpd(IpdMm));

            // Careful: the SDK inverts the sign — negative widens, positive narrows.
            if (FovScale != 0) NativeModule.Instance.ChangeFov(FovScale);

            NativeModule.Instance.ActiveFovControlView(ShowFovControlView);
        }

        public static float NormaliseIpd(float mm)
        {
            return Mathf.Clamp01((mm - IpdMinMm) / (IpdMaxMm - IpdMinMm));
        }

        /// <summary>Makes the current heading the new straight-ahead.</summary>
        public void Recenter()
        {
            NativeModule.Instance.ResetGlassQuat();
            _bodyYaw = 0f;
            if (BodyRig != null) BodyRig.localRotation = Quaternion.identity;
        }

        public void SetLuminance(int mode)
        {
            LuminanceMode = Mathf.Clamp(mode, 0, 3);
            NativeModule.Instance.SetLuminanceMode(LuminanceMode);
        }

        public void SetIpd(float mm)
        {
            IpdMm = Mathf.Clamp(mm, IpdMinMm, IpdMaxMm);
            NativeModule.Instance.SetInterpupilDistance(NormaliseIpd(IpdMm));
        }

        /// <summary>Reads the device's current IPD in millimetres.</summary>
        public float ReadIpd()
        {
            return NativeModule.Instance.GetInterpupilDistance();
        }

        // -------------------------------------------------------------------
        // Panel construction
        // -------------------------------------------------------------------

        /// <summary>
        /// Spherical (yaw, pitch, distance) to Unity's left-handed, Y-up,
        /// +Z-forward space. Yaw is positive to the right, pitch positive up.
        /// </summary>
        public static Vector3 PolarToLocal(float yawDeg, float pitchDeg, float distanceM)
        {
            float yaw = yawDeg * Mathf.Deg2Rad;
            float pitch = pitchDeg * Mathf.Deg2Rad;
            float cosPitch = Mathf.Cos(pitch);
            return new Vector3(
                distanceM * Mathf.Sin(yaw) * cosPitch,
                distanceM * Mathf.Sin(pitch),
                distanceM * Mathf.Cos(yaw) * cosPitch);
        }

        void BuildPanels()
        {
            foreach (var spec in Panels)
            {
                var parent = spec.Anchor == AnchorMode.Head ? Head : BodyRig;
                var go = PanelPrefab != null
                    ? Instantiate(PanelPrefab, parent)
                    : GameObject.CreatePrimitive(PrimitiveType.Quad);
                if (PanelPrefab == null) go.transform.SetParent(parent, false);

                go.name = "Panel_" + spec.Title;
                go.transform.localPosition = PolarToLocal(spec.YawDeg, spec.PitchDeg, spec.DistanceM);

                if (spec.FaceWearer)
                {
                    // Turn the quad to face the wearer. Without this, off-axis
                    // panels are seen at a slant and the far edge reads blurry.
                    go.transform.localRotation = Quaternion.LookRotation(
                        go.transform.localPosition.normalized, Vector3.up);
                }
                else
                {
                    go.transform.localRotation = Quaternion.identity;
                }
                go.transform.localRotation *= Quaternion.Euler(0f, 0f, spec.RollDeg);

                // A Unity quad is 1x1 m, so local scale is the physical size.
                go.transform.localScale = new Vector3(spec.WidthM, spec.HeightM, 1f);

                // Nudge along the view ray by z-order so coplanar panels have a
                // deterministic draw order instead of z-fighting.
                go.transform.localPosition -= go.transform.localPosition.normalized * (spec.ZOrder * 0.001f);

                SetOpacity(go, spec.Opacity);
                go.SetActive(spec.Visible);
                _instances[spec.Id] = go;
            }
        }

        static void SetOpacity(GameObject go, float opacity)
        {
            var r = go.GetComponent<Renderer>();
            if (r == null || r.material == null) return;
            if (r.material.HasProperty("_Color"))
            {
                var c = r.material.color;
                c.a = opacity;
                r.material.color = c;
            }
        }

        // -------------------------------------------------------------------
        // Views and focus
        // -------------------------------------------------------------------

        public void ActivateView(string viewId)
        {
            ViewSpec target = null;
            foreach (var v in Views) if (v.Id == viewId) { target = v; break; }
            if (target == null) return;

            _activeView = target;
            var wanted = new HashSet<string>(target.PanelIds);
            foreach (var kv in _instances)
            {
                bool on = wanted.Contains(kv.Key) && _specs[kv.Key].Visible;
                kv.Value.SetActive(on);
            }

            if (!string.IsNullOrEmpty(target.FocusedPanelId)) FocusPanel(target.FocusedPanelId);
            if (target.RecenterOnEnter) Recenter();
        }

        public void ActivateViewByIndex(int index)
        {
            if (index < 0 || index >= Views.Length) return;
            ActivateView(Views[index].Id);
        }

        public void NextView()
        {
            if (_activeView == null) { ActivateViewByIndex(0); return; }
            for (int i = 0; i < Views.Length; i++)
            {
                if (Views[i].Id == _activeView.Id)
                {
                    ActivateViewByIndex((i + 1) % Views.Length);
                    return;
                }
            }
        }

        public void PreviousView()
        {
            if (_activeView == null) { ActivateViewByIndex(0); return; }
            for (int i = 0; i < Views.Length; i++)
            {
                if (Views[i].Id == _activeView.Id)
                {
                    ActivateViewByIndex((i - 1 + Views.Length) % Views.Length);
                    return;
                }
            }
        }

        public void FocusPanel(string panelId)
        {
            _focusedPanelId = panelId;
            foreach (var kv in _instances)
            {
                var spec = _specs[kv.Key];
                float target = spec.Opacity;
                if (spec.DimWhenUnfocused && kv.Key != panelId) target = spec.Opacity * 0.35f;
                SetOpacity(kv.Value, target);
            }
        }

        public void FocusNextPanel()
        {
            if (_activeView == null || _activeView.PanelIds.Length == 0) return;
            int at = Array.IndexOf(_activeView.PanelIds, _focusedPanelId);
            FocusPanel(_activeView.PanelIds[(at + 1) % _activeView.PanelIds.Length]);
        }

        // -------------------------------------------------------------------
        // Body anchor follow
        // -------------------------------------------------------------------

        void Update()
        {
            if (BodyRig == null || Head == null) return;

            // Body-anchored panels trail the head: inside the deadzone they hold
            // still so small movements do not drag the whole workspace around,
            // and past it they ease toward the new heading.
            float headYaw = Head.eulerAngles.y;
            float delta = Mathf.DeltaAngle(_bodyYaw, headYaw);
            if (Mathf.Abs(delta) > FollowDeadzoneDeg)
            {
                float overshoot = delta - Mathf.Sign(delta) * FollowDeadzoneDeg;
                float k = FollowLagSeconds > 0f
                    ? 1f - Mathf.Exp(-Time.deltaTime / FollowLagSeconds)
                    : 1f;
                _bodyYaw += overshoot * k;
                BodyRig.localRotation = Quaternion.Euler(0f, _bodyYaw, 0f);
            }
        }
    }
}
`
}

/**
 * A description of the bridge protocol, generated alongside the profile so the
 * companion and the app can never drift apart silently.
 */
export function bridgeSnippet(profile: Profile): string {
  const ipd = ipdMmToNormalised(profile.device.ipdMm, getDevice(profile.deviceId).ipdRangeMm)
  return `# Bridge quick reference

Companion listens on ws://<host>:8787 and speaks JSON, one op per frame.

## Ops this profile would send on connect

{"v":1,"op":"device.setLuminance","mode":${profile.device.luminanceMode}}
  -> NativeModule.Instance.SetLuminanceMode(${profile.device.luminanceMode})

{"v":1,"op":"device.setIpd","ipdMm":${profile.device.ipdMm}}
  -> NativeModule.Instance.SetInterpupilDistance(${ipd.toFixed(4)}f)

{"v":1,"op":"device.changeFov","scale":${profile.device.fovScale}}
  -> NativeModule.Instance.ChangeFov(${profile.device.fovScale})   // negative widens

{"v":1,"op":"device.fovControlView","active":${profile.device.fovControlView}}
  -> NativeModule.Instance.ActiveFovControlView(${profile.device.fovControlView})

{"v":1,"op":"device.recenter"}
  -> NativeModule.Instance.ResetGlassQuat()

## Events the companion pushes back

{"ev":"hello","name":"rayneo-companion","protocol":1}
{"ev":"pose","yawDeg":0.0,"pitchDeg":0.0,"rollDeg":0.0}
{"ev":"ipd","ipdMm":${profile.device.ipdMm}}
{"ev":"log","line":"..."}
`
}

export function androidIntent(profile: Profile): string {
  return `# Hand a profile to the companion over adb
adb push profile.json /sdcard/Download/profile.json
adb shell am start -n com.example.rayneocompanion/.MainActivity \\
  -a android.intent.action.VIEW \\
  -d file:///sdcard/Download/profile.json \\
  --es profileName "${profile.name.replace(/"/g, '\\"')}"
`
}

/** A human-readable summary of a workspace, useful for sharing or a changelog. */
export function workspaceReport(profile: Profile, ws: Workspace): string {
  const device = getDevice(profile.deviceId)
  const ppd = devicePpd(device)
  const lines: string[] = [
    `# ${ws.name}`,
    '',
    ws.description ?? '',
    '',
    `Device: ${device.name} · ${device.panelWidthPx}x${device.panelHeightPx} per eye · ${device.fovDiagonalDeg}° diagonal FOV (${ppd.fov.horizontalDeg.toFixed(1)}° x ${ppd.fov.verticalDeg.toFixed(1)}°) · ${ppd.center.toFixed(1)} px/deg on axis`,
    '',
    '## Panels',
    '',
    '| Panel | Source | Yaw | Pitch | Distance | Diagonal | Angular | Sharpness | Anchor |',
    '|---|---|---|---|---|---|---|---|---|',
  ]
  for (const p of ws.panels) {
    const a = analysePanel(p, device)
    lines.push(
      `| ${p.title} | ${p.source} | ${p.yawDeg.toFixed(0)}° | ${p.pitchDeg.toFixed(
        0,
      )}° | ${p.distanceM.toFixed(2)} m | ${p.diagonalIn.toFixed(
        0,
      )}" | ${a.angularWidthDeg.toFixed(1)}° x ${a.angularHeightDeg.toFixed(
        1,
      )}° | ${Math.round(a.sharpness * 100)}% | ${p.anchor} |`,
    )
  }
  lines.push('', '## Views', '')
  for (const v of ws.views) {
    const names = v.panelIds
      .map((id) => ws.panels.find((p) => p.id === id)?.title ?? id)
      .join(', ')
    lines.push(
      `- **${v.name}**${v.hotkey ? ` (\`${v.hotkey}\`)` : ''} — ${names}${
        v.recenterOnEnter ? ' · recentres on enter' : ''
      }`,
    )
    if (v.notes) lines.push(`  - ${v.notes}`)
  }
  return lines.join('\n')
}

export function download(filename: string, content: string, type = 'application/json') {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'profile'
}

/** Unused panels are the most common thing to leave behind while iterating. */
export function findOrphanPanels(ws: Workspace): Panel[] {
  const used = new Set(ws.views.flatMap((v) => v.panelIds))
  return ws.panels.filter((p) => !used.has(p.id))
}
