// <auto-generated>
// RayNeo Air 4 Pro workspace applier
//
// Generated by the RayNeo Workspace Configurator from profile "Reference profile"
// Workspace: "Desk"   Target: RayNeo Air 4 Pro
//
// Drop this on a GameObject in a Unity project that has the RayNeo Air SDK
// (Ffalcon XR Unity SDK) imported, assign PanelPrefab, and press play. Device
// settings go out through NativeModule; panels are built as world-space quads.
//
// Device reference:
//   Per-eye resolution   1920 x 1080
//   Field of view        47° diagonal (41.5° x 24.1°)
//   On-axis density      44.2 px/deg
//   Tracking            3DoF — orientation only, no positional tracking
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;

namespace RayNeo.Workspace
{
    public enum AnchorMode { Head, Body, World }

    [Serializable]
    public class PanelSpec
    {
        public string Id;
        public string Title;
        public string Source;
        public float YawDeg, PitchDeg, RollDeg;
        public float DistanceM;
        public float WidthM, HeightM;
        public int SourceWidthPx, SourceHeightPx;
        public AnchorMode Anchor;
        public bool FaceWearer;
        public float Opacity;
        public float CurvatureDeg;
        public int ZOrder;
        public bool Visible;
        public bool DimWhenUnfocused;
    }

    [Serializable]
    public class ViewSpec
    {
        public string Id;
        public string Name;
        public string Hotkey;
        public bool RecenterOnEnter;
        public string FocusedPanelId;
        public string[] PanelIds;
    }

    public class RayNeoWorkspaceApplier : MonoBehaviour
    {
        [Header("Scene wiring")]
        [Tooltip("Quad prefab used for every panel. Needs a MeshRenderer.")]
        public GameObject PanelPrefab;

        [Tooltip("The Head transform from the XRPlugin prefab.")]
        public Transform Head;

        [Tooltip("Parent for Body-anchored panels. Follows head yaw with lag.")]
        public Transform BodyRig;

        [Header("Device settings")]
        [Range(0, 3)] public int LuminanceMode = 2;
        [Range(60f, 70f)] public float IpdMm = 64f;
        [Range(-10, 10)] public int FovScale = 0;
        public bool ShowFovControlView = false;

        [Header("Body anchor follow")]
        public float FollowDeadzoneDeg = 12f;
        public float FollowLagSeconds = 0.45f;

        // Hardware constants for the target device.
        public const int PanelWidthPx = 1920;
        public const int PanelHeightPx = 1080;
        public const float FovDiagonalDeg = 47f;
        public const float FovHorizontalDeg = 41.5106f;
        public const float FovVerticalDeg = 24.0674f;
        public const float IpdMinMm = 60f;
        public const float IpdMaxMm = 70f;

        public static readonly PanelSpec[] Panels = new []
        {
            new PanelSpec {
                Id = "panel-desk-main",
                Title = "Main",
                Source = "usb-c-display",
                YawDeg = 0f, PitchDeg = 0f, RollDeg = 0f,
                DistanceM = 4f,
                WidthM = 2.3688f, HeightM = 1.3324f,
                SourceWidthPx = 1500, SourceHeightPx = 844,
                Anchor = AnchorMode.Body,
                FaceWearer = true,
                Opacity = 1f, CurvatureDeg = 0f,
                ZOrder = 0, Visible = true,
                DimWhenUnfocused = true,
                // 33.0° x 18.9° · 100% of source resolution
            },
            new PanelSpec {
                Id = "panel-desk-reference",
                Title = "Reference",
                Source = "browser",
                YawDeg = -29f, PitchDeg = 0f, RollDeg = 0f,
                DistanceM = 4f,
                WidthM = 1.5541f, HeightM = 0.8742f,
                SourceWidthPx = 984, SourceHeightPx = 554,
                Anchor = AnchorMode.Body,
                FaceWearer = true,
                Opacity = 1f, CurvatureDeg = 0f,
                ZOrder = 1, Visible = true,
                DimWhenUnfocused = true,
                // 22.0° x 12.5° · 100% of source resolution
            },
            new PanelSpec {
                Id = "panel-desk-comms",
                Title = "Comms",
                Source = "cast",
                YawDeg = 29f, PitchDeg = 0f, RollDeg = 0f,
                DistanceM = 4f,
                WidthM = 1.5541f, HeightM = 0.8742f,
                SourceWidthPx = 984, SourceHeightPx = 554,
                Anchor = AnchorMode.Body,
                FaceWearer = true,
                Opacity = 1f, CurvatureDeg = 0f,
                ZOrder = 2, Visible = true,
                DimWhenUnfocused = true,
                // 22.0° x 12.5° · 100% of source resolution
            },
            new PanelSpec {
                Id = "panel-desk-scratch",
                Title = "Scratch",
                Source = "widget",
                YawDeg = 0f, PitchDeg = -20f, RollDeg = 0f,
                DistanceM = 4f,
                WidthM = 1.4102f, HeightM = 0.7932f,
                SourceWidthPx = 894, SourceHeightPx = 502,
                Anchor = AnchorMode.Body,
                FaceWearer = true,
                Opacity = 0.9f, CurvatureDeg = 0f,
                ZOrder = 3, Visible = true,
                DimWhenUnfocused = true,
                // 20.0° x 11.3° · 100% of source resolution
            },
        };

        public static readonly ViewSpec[] Views = new []
        {
            new ViewSpec {
                Id = "view-desk-triple",
                Name = "Triple",
                Hotkey = "1",
                RecenterOnEnter = false,
                FocusedPanelId = "panel-desk-main",
                PanelIds = new [] { "panel-desk-main", "panel-desk-reference", "panel-desk-comms" },
            },
            new ViewSpec {
                Id = "view-desk-focus",
                Name = "Focus",
                Hotkey = "2",
                RecenterOnEnter = false,
                FocusedPanelId = "panel-desk-main",
                PanelIds = new [] { "panel-desk-main" },
            },
            new ViewSpec {
                Id = "view-desk-deep-work",
                Name = "Deep work",
                Hotkey = "3",
                RecenterOnEnter = true,
                FocusedPanelId = "panel-desk-main",
                PanelIds = new [] { "panel-desk-main", "panel-desk-scratch" },
            },
        };

        private readonly Dictionary<string, GameObject> _instances = new Dictionary<string, GameObject>();
        private readonly Dictionary<string, PanelSpec> _specs = new Dictionary<string, PanelSpec>();
        private ViewSpec _activeView;
        private string _focusedPanelId;
        private float _bodyYaw;

        void Start()
        {
            foreach (var p in Panels) _specs[p.Id] = p;
            ApplyDeviceSettings();
            BuildPanels();
            ActivateView("view-desk-triple");
        }

        // -------------------------------------------------------------------
        // Device settings — these are the calls the RayNeo Air SDK exposes.
        // -------------------------------------------------------------------

        public void ApplyDeviceSettings()
        {
            // Four discrete brightness steps; the SDK has no continuous control.
            NativeModule.Instance.SetLuminanceMode(LuminanceMode);

            // SetInterpupilDistance takes a normalised 0..1 mapped onto 60-70 mm.
            NativeModule.Instance.SetInterpupilDistance(NormaliseIpd(IpdMm));

            // Careful: the SDK inverts the sign — negative widens, positive narrows.
            if (FovScale != 0) NativeModule.Instance.ChangeFov(FovScale);

            NativeModule.Instance.ActiveFovControlView(ShowFovControlView);
        }

        public static float NormaliseIpd(float mm)
        {
            return Mathf.Clamp01((mm - IpdMinMm) / (IpdMaxMm - IpdMinMm));
        }

        /// <summary>Makes the current heading the new straight-ahead.</summary>
        public void Recenter()
        {
            NativeModule.Instance.ResetGlassQuat();
            _bodyYaw = 0f;
            if (BodyRig != null) BodyRig.localRotation = Quaternion.identity;
        }

        public void SetLuminance(int mode)
        {
            LuminanceMode = Mathf.Clamp(mode, 0, 3);
            NativeModule.Instance.SetLuminanceMode(LuminanceMode);
        }

        public void SetIpd(float mm)
        {
            IpdMm = Mathf.Clamp(mm, IpdMinMm, IpdMaxMm);
            NativeModule.Instance.SetInterpupilDistance(NormaliseIpd(IpdMm));
        }

        /// <summary>Reads the device's current IPD in millimetres.</summary>
        public float ReadIpd()
        {
            return NativeModule.Instance.GetInterpupilDistance();
        }

        // -------------------------------------------------------------------
        // Panel construction
        // -------------------------------------------------------------------

        /// <summary>
        /// Spherical (yaw, pitch, distance) to Unity's left-handed, Y-up,
        /// +Z-forward space. Yaw is positive to the right, pitch positive up.
        /// </summary>
        public static Vector3 PolarToLocal(float yawDeg, float pitchDeg, float distanceM)
        {
            float yaw = yawDeg * Mathf.Deg2Rad;
            float pitch = pitchDeg * Mathf.Deg2Rad;
            float cosPitch = Mathf.Cos(pitch);
            return new Vector3(
                distanceM * Mathf.Sin(yaw) * cosPitch,
                distanceM * Mathf.Sin(pitch),
                distanceM * Mathf.Cos(yaw) * cosPitch);
        }

        void BuildPanels()
        {
            foreach (var spec in Panels)
            {
                var parent = spec.Anchor == AnchorMode.Head ? Head : BodyRig;
                var go = PanelPrefab != null
                    ? Instantiate(PanelPrefab, parent)
                    : GameObject.CreatePrimitive(PrimitiveType.Quad);
                if (PanelPrefab == null) go.transform.SetParent(parent, false);

                go.name = "Panel_" + spec.Title;
                go.transform.localPosition = PolarToLocal(spec.YawDeg, spec.PitchDeg, spec.DistanceM);

                if (spec.FaceWearer)
                {
                    // Turn the quad to face the wearer. Without this, off-axis
                    // panels are seen at a slant and the far edge reads blurry.
                    go.transform.localRotation = Quaternion.LookRotation(
                        go.transform.localPosition.normalized, Vector3.up);
                }
                else
                {
                    go.transform.localRotation = Quaternion.identity;
                }
                go.transform.localRotation *= Quaternion.Euler(0f, 0f, spec.RollDeg);

                // A Unity quad is 1x1 m, so local scale is the physical size.
                go.transform.localScale = new Vector3(spec.WidthM, spec.HeightM, 1f);

                // Nudge along the view ray by z-order so coplanar panels have a
                // deterministic draw order instead of z-fighting.
                go.transform.localPosition -= go.transform.localPosition.normalized * (spec.ZOrder * 0.001f);

                SetOpacity(go, spec.Opacity);
                go.SetActive(spec.Visible);
                _instances[spec.Id] = go;
            }
        }

        static void SetOpacity(GameObject go, float opacity)
        {
            var r = go.GetComponent<Renderer>();
            if (r == null || r.material == null) return;
            if (r.material.HasProperty("_Color"))
            {
                var c = r.material.color;
                c.a = opacity;
                r.material.color = c;
            }
        }

        // -------------------------------------------------------------------
        // Views and focus
        // -------------------------------------------------------------------

        public void ActivateView(string viewId)
        {
            ViewSpec target = null;
            foreach (var v in Views) if (v.Id == viewId) { target = v; break; }
            if (target == null) return;

            _activeView = target;
            var wanted = new HashSet<string>(target.PanelIds);
            foreach (var kv in _instances)
            {
                bool on = wanted.Contains(kv.Key) && _specs[kv.Key].Visible;
                kv.Value.SetActive(on);
            }

            if (!string.IsNullOrEmpty(target.FocusedPanelId)) FocusPanel(target.FocusedPanelId);
            if (target.RecenterOnEnter) Recenter();
        }

        public void ActivateViewByIndex(int index)
        {
            if (index < 0 || index >= Views.Length) return;
            ActivateView(Views[index].Id);
        }

        public void NextView()
        {
            if (_activeView == null) { ActivateViewByIndex(0); return; }
            for (int i = 0; i < Views.Length; i++)
            {
                if (Views[i].Id == _activeView.Id)
                {
                    ActivateViewByIndex((i + 1) % Views.Length);
                    return;
                }
            }
        }

        public void PreviousView()
        {
            if (_activeView == null) { ActivateViewByIndex(0); return; }
            for (int i = 0; i < Views.Length; i++)
            {
                if (Views[i].Id == _activeView.Id)
                {
                    ActivateViewByIndex((i - 1 + Views.Length) % Views.Length);
                    return;
                }
            }
        }

        public void FocusPanel(string panelId)
        {
            _focusedPanelId = panelId;
            foreach (var kv in _instances)
            {
                var spec = _specs[kv.Key];
                float target = spec.Opacity;
                if (spec.DimWhenUnfocused && kv.Key != panelId) target = spec.Opacity * 0.35f;
                SetOpacity(kv.Value, target);
            }
        }

        public void FocusNextPanel()
        {
            if (_activeView == null || _activeView.PanelIds.Length == 0) return;
            int at = Array.IndexOf(_activeView.PanelIds, _focusedPanelId);
            FocusPanel(_activeView.PanelIds[(at + 1) % _activeView.PanelIds.Length]);
        }

        // -------------------------------------------------------------------
        // Body anchor follow
        // -------------------------------------------------------------------

        void Update()
        {
            if (BodyRig == null || Head == null) return;

            // Body-anchored panels trail the head: inside the deadzone they hold
            // still so small movements do not drag the whole workspace around,
            // and past it they ease toward the new heading.
            float headYaw = Head.eulerAngles.y;
            float delta = Mathf.DeltaAngle(_bodyYaw, headYaw);
            if (Mathf.Abs(delta) > FollowDeadzoneDeg)
            {
                float overshoot = delta - Mathf.Sign(delta) * FollowDeadzoneDeg;
                float k = FollowLagSeconds > 0f
                    ? 1f - Mathf.Exp(-Time.deltaTime / FollowLagSeconds)
                    : 1f;
                _bodyYaw += overshoot * k;
                BodyRig.localRotation = Quaternion.Euler(0f, _bodyYaw, 0f);
            }
        }
    }
}
